#ifndef DECLARATIONS_EPOS
#define DECLARATIONS_EPOS

#include "EPOS_NETWORK.h"
#include "AXIS.h"
#include "FORCE_SENSOR.h"

//ENDEREÇAMENTO DA BASE DE DADOS CAN
char *CAN_INTERFACE = "CAN1";
char *CAN_DATABASE = "database";
char *CAN_CLUSTER = "NETCAN";
char *NET_ID_SERVO_01 = "1";
char *NET_ID_SERVO_02 = "2";
char *NET_ID_SENSOR = "5";

//INICIALIZAÇÃO DA REDE CAN
EPOS_NETWORK epos(CAN_INTERFACE, CAN_DATABASE, CAN_CLUSTER);

//INICIALIZAÇÃO DAS EPOS
AXIS eixo_out(CAN_INTERFACE, CAN_DATABASE, CAN_CLUSTER, NET_ID_SERVO_02);
AXIS eixo_in(CAN_INTERFACE, CAN_DATABASE, CAN_CLUSTER, NET_ID_SERVO_01);

int ZERO_01 = 0; // Zero do eixo_out
int ZERO_02 = 0; // Zero do eixo_in

//Inicialização do sensor de for�a
FORCE_SENSOR sensor6D(CAN_INTERFACE, CAN_DATABASE, CAN_CLUSTER, NET_ID_SENSOR);

#endif /* DECLARATIONS_EPOS */